# Generated by Django 3.2.8 on 2021-11-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_enlacesapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250, unique=True, verbose_name='group url')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='group name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='group description')),
                ('image', models.CharField(blank=True, max_length=200, null=True, verbose_name='group image')),
                ('created', models.DateField(verbose_name='date published')),
            ],
        ),
    ]
