# Generated by Django 3.2.8 on 2021-11-06 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_groups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Link_Groups',
        ),
    ]
