# Generated by Django 3.2.8 on 2021-11-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_link_groups_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link_groups',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
