# Generated by Django 3.2.8 on 2021-11-07 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_link_groups_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link_Groups',
            new_name='Link_Group',
        ),
    ]
